import type { Tastemaker, CuratedList, Restaurant, Tag } from "./types";

// ── Tags ──────────────────────────────────────────────────────────────────────

const TAGS: Record<string, Tag> = {
  naturalWine: { id: "t1", name: "natural wine", level: 3 },
  smallPlates: { id: "t2", name: "small plates", level: 2 },
  japanese:    { id: "t3", name: "japanese", level: 2 },
  pasta:       { id: "t4", name: "pasta", level: 3 },
  pizza:       { id: "t5", name: "pizza", level: 4 },
  brunch:      { id: "t6", name: "brunch", level: 1 },
  italian:     { id: "t7", name: "italian", level: 3 },
  vegetarian:  { id: "t8", name: "vegetarian", level: 2 },
  tasting:     { id: "t9", name: "tasting menu", level: 5 },
  latenite:    { id: "t10", name: "late night", level: 1 },
  portuguese:  { id: "t11", name: "portuguese", level: 2 },
  taiwanese:   { id: "t12", name: "taiwanese", level: 2 },
  ramen:       { id: "t13", name: "ramen", level: 3 },
  deli:        { id: "t14", name: "jewish deli", level: 2 },
};

// ── Restaurants ───────────────────────────────────────────────────────────────

const RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    slug: "cervos",
    name: "Cervo's",
    address: "43 Canal St",
    neighborhood: "Lower East Side",
    city: "New York, NY",
    cuisine: "Portuguese-Mediterranean",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    tags: [TAGS.portuguese, TAGS.smallPlates, TAGS.naturalWine],
    foursquareId: "5b3a8c8a",
    latitude: 40.7133,
    longitude: -73.9990,
  },
  {
    id: "r2",
    slug: "win-son",
    name: "Win Son",
    address: "159 Graham Ave",
    neighborhood: "Williamsburg",
    city: "New York, NY",
    cuisine: "Taiwanese-American",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    tags: [TAGS.taiwanese, TAGS.smallPlates],
    foursquareId: "5b3a8c8b",
    latitude: 40.7136,
    longitude: -73.9436,
  },
  {
    id: "r3",
    slug: "scarrs-pizza",
    name: "Scarr's Pizza",
    address: "22 Orchard St",
    neighborhood: "Lower East Side",
    city: "New York, NY",
    cuisine: "NY Slice",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    tags: [TAGS.pizza, TAGS.latenite],
    foursquareId: "5b3a8c8c",
    latitude: 40.7157,
    longitude: -73.9918,
  },
  {
    id: "r4",
    slug: "lilia",
    name: "Lilia",
    address: "567 Union Ave",
    neighborhood: "Williamsburg",
    city: "New York, NY",
    cuisine: "Italian",
    imageUrl: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=800&q=80",
    tags: [TAGS.pasta, TAGS.italian],
    foursquareId: "5b3a8c8d",
    latitude: 40.7185,
    longitude: -73.9516,
  },
  {
    id: "r5",
    slug: "superiority-burger",
    name: "Superiority Burger",
    address: "430 E 9th St",
    neighborhood: "East Village",
    city: "New York, NY",
    cuisine: "Vegetarian",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    tags: [TAGS.vegetarian, TAGS.smallPlates],
    foursquareId: "5b3a8c8e",
    latitude: 40.7268,
    longitude: -73.9806,
  },
  {
    id: "r6",
    slug: "ivan-ramen",
    name: "Ivan Ramen",
    address: "25 Clinton St",
    neighborhood: "Lower East Side",
    city: "New York, NY",
    cuisine: "Japanese Ramen",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    tags: [TAGS.ramen, TAGS.japanese],
    foursquareId: "5b3a8c8f",
    latitude: 40.7168,
    longitude: -73.9849,
  },
  {
    id: "r7",
    slug: "russ-daughters-cafe",
    name: "Russ & Daughters Cafe",
    address: "127 Orchard St",
    neighborhood: "Lower East Side",
    city: "New York, NY",
    cuisine: "Jewish Deli",
    imageUrl: "https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=800&q=80",
    tags: [TAGS.deli, TAGS.brunch],
    foursquareId: "5b3a8c90",
    latitude: 40.7197,
    longitude: -73.9883,
  },
  {
    id: "r8",
    slug: "don-angie",
    name: "Don Angie",
    address: "103 Greenwich Ave",
    neighborhood: "West Village",
    city: "New York, NY",
    cuisine: "Italian-American",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    tags: [TAGS.italian, TAGS.pasta, TAGS.tasting],
    foursquareId: "5b3a8c91",
    latitude: 40.7350,
    longitude: -74.0026,
  },
];

// ── Curated Lists ─────────────────────────────────────────────────────────────

const LISTS: Record<string, CuratedList> = {
  lesHiddenGems: {
    id: "l1",
    slug: "hidden-gems-lower-east-side",
    title: "Hidden Gems of the Lower East Side",
    description:
      "The restaurants that haven't made it into the algorithm yet. Regulars only — until now.",
    coverImageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    restaurantCount: 4,
    restaurants: [RESTAURANTS[0], RESTAURANTS[2], RESTAURANTS[5], RESTAURANTS[6]],
    createdAt: "2024-09-15",
  },
  naturalWine: {
    id: "l2",
    slug: "natural-wine-bars-worth-knowing",
    title: "Natural Wine Bars Worth Knowing",
    description:
      "Orange wines, pét-nats, and skin-contact bottles in rooms that feel like someone's living room.",
    coverImageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&q=80",
    restaurantCount: 3,
    restaurants: [RESTAURANTS[0], RESTAURANTS[1], RESTAURANTS[4]],
    createdAt: "2024-11-02",
  },
  brooklynBest: {
    id: "l3",
    slug: "brooklyn-best-2024",
    title: "Brooklyn's Best New Openings",
    description:
      "A year of eating through the borough. These are the ones that stuck.",
    coverImageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80",
    restaurantCount: 3,
    restaurants: [RESTAURANTS[1], RESTAURANTS[3], RESTAURANTS[7]],
    createdAt: "2024-12-01",
  },
  spotsWorthWait: {
    id: "l4",
    slug: "spots-worth-the-wait",
    title: "Spots Worth the Wait",
    description:
      "No reservations, long lines, and absolutely worth it every time.",
    coverImageUrl: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=1200&q=80",
    restaurantCount: 2,
    restaurants: [RESTAURANTS[3], RESTAURANTS[2]],
    createdAt: "2025-01-18",
  },
  plantBased: {
    id: "l5",
    slug: "plant-based-nyc",
    title: "Plant-Based NYC (No Sad Salads)",
    description:
      "Vegetarian and vegan restaurants where the food is the point, not the restriction.",
    coverImageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=80",
    restaurantCount: 2,
    restaurants: [RESTAURANTS[4], RESTAURANTS[5]],
    createdAt: "2025-02-05",
  },
  tastingMenus: {
    id: "l6",
    slug: "tasting-menus-worth-splurging",
    title: "Tasting Menus Worth Splurging On",
    description:
      "When the occasion calls for it. These are the meals you'll talk about for years.",
    coverImageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=1200&q=80",
    restaurantCount: 2,
    restaurants: [RESTAURANTS[7], RESTAURANTS[3]],
    createdAt: "2025-03-14",
  },
};

// ── Tastemakers ───────────────────────────────────────────────────────────────

export const STUB_TASTEMAKERS: Tastemaker[] = [
  {
    id: "u1",
    slug: "maya-chen",
    name: "Maya Chen",
    username: "mayachen",
    bio: "NYC-based food writer covering the intersection of culture and cuisine. Former Bon Appétit contributor. I eat everywhere so you know where to go.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    location: "New York, NY",
    followerCount: 1240,
    listCount: 2,
    level: 4,
    lists: [LISTS.lesHiddenGems, LISTS.naturalWine],
    tags: [TAGS.naturalWine, TAGS.japanese, TAGS.smallPlates],
  },
  {
    id: "u2",
    slug: "marcus-williams",
    name: "Marcus Williams",
    username: "marcuseats",
    bio: "Chef-turned-consultant. I find restaurants before they blow up. Brooklyn by way of New Orleans. Opinions are free, reservations are not.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    location: "Brooklyn, NY",
    followerCount: 892,
    listCount: 2,
    level: 3,
    lists: [LISTS.brooklynBest, LISTS.spotsWorthWait],
    tags: [TAGS.italian, TAGS.pizza, TAGS.brunch],
  },
  {
    id: "u3",
    slug: "priya-patel",
    name: "Priya Patel",
    username: "priyaeats",
    bio: "Vegetarian food lover navigating NYC's plant-based scene. Also somehow a sucker for 14-course tasting menus. Not a contradiction.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    location: "New York, NY",
    followerCount: 567,
    listCount: 2,
    level: 2,
    lists: [LISTS.plantBased, LISTS.tastingMenus],
    tags: [TAGS.vegetarian, TAGS.tasting, TAGS.smallPlates],
  },
];

export const STUB_RESTAURANTS: Restaurant[] = RESTAURANTS;
export const STUB_LISTS: CuratedList[] = Object.values(LISTS);
