import { notFound } from "next/navigation";
import { fetchMarkdown, getDoc, getDocsRegistry, groupBySection, statusBadge } from "@/lib/docs";
import { renderMarkdown } from "@/lib/markdown";
import { ADMIN_THEME as t } from "@/lib/admin-theme";


const TONE: Record<string, string> = {
  ok: t.accent, warn: t.warn, accent: t.accent, muted: t.muted,
};

export default async function DocPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const doc = getDoc(id);
  if (!doc) notFound();

  const markdown = await fetchMarkdown(doc.source);
  const groups = groupBySection(getDocsRegistry());
  const badge = statusBadge(doc);

  return (
    <div style={{ display: "flex", minHeight: "100vh", fontFamily: t.font }}>
      {/* Sidebar — wide enough that titles aren't truncated to uselessness */}
      <aside
        style={{
          width: 268,
          borderRight: `1px solid ${t.border}`,
          padding: "20px 0",
          flexShrink: 0,
          maxHeight: "100vh",
          overflowY: "auto",
        }}
      >
        <a
          href="/admin/docs"
          style={{ display: "block", padding: "6px 16px 14px", fontSize: 11, color: t.dim, textDecoration: "none" }}
        >
          ← All docs
        </a>

        {groups.map((g) => (
          <div key={g.section}>
            <div
              title={g.blurb}
              style={{
                padding: "10px 16px 4px",
                fontSize: 10,
                color: t.dim,
                textTransform: "uppercase",
                letterSpacing: 1,
              }}
            >
              {g.label}
            </div>
            {g.docs.map((d) => (
              <a
                key={d.id}
                href={`/admin/docs/${d.id}`}
                title={`${d.title}\n${d.path}`}
                style={{
                  display: "block",
                  padding: "7px 16px",
                  fontSize: 11.5,
                  color: d.id === id ? t.text : t.muted,
                  textDecoration: "none",
                  background: d.id === id ? `${t.accent}12` : "transparent",
                  borderLeft: d.id === id ? `2px solid ${t.accent}` : "2px solid transparent",
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                }}
              >
                {d.title}
              </a>
            ))}
          </div>
        ))}
      </aside>

      <main style={{ flex: 1, padding: "28px 40px", overflowY: "auto", maxWidth: 900 }}>
        {/* Metadata strip */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 10,
            flexWrap: "wrap",
            fontSize: 10.5,
            color: t.dim,
            marginBottom: 20,
            paddingBottom: 12,
            borderBottom: `1px solid ${t.border}`,
          }}
        >
          <span style={{ color: t.accent }}>{doc.id}</span>
          {doc.docType && <span>· {doc.docType}</span>}
          {badge && <span style={{ color: TONE[badge.tone] }}>· {badge.label}</span>}
          {doc.generated && <span title="Regenerated by npm run docs:refresh">· generated</span>}
          {doc.tags.length > 0 && <span>· {doc.tags.join(" ")}</span>}
          <span style={{ marginLeft: "auto", opacity: 0.7 }}>{doc.path}</span>
        </div>

        {doc.generated && (
          <div
            style={{
              margin: "0 0 20px",
              padding: "10px 14px",
              border: `1px solid ${t.border}`,
              borderLeft: `3px solid ${t.warn}`,
              borderRadius: 4,
              fontSize: 11.5,
              color: t.muted,
            }}
          >
            Generated file — do not hand-edit. Regenerate with <code>npm run docs:refresh</code>.
          </div>
        )}

        {markdown ? (
          <>
            <style>{`
              .md-body h1, .md-body h2 { color: ${t.text}; font-weight: 600; line-height: 1.3; }
              .md-body h3 { color: ${t.muted}; font-weight: 600; line-height: 1.3; }
              .md-body h4, .md-body h5, .md-body h6 { color: ${t.dim}; font-weight: 600; line-height: 1.3; }
              .md-body h1 { font-size: 24px; margin: 0 0 20px; }
              .md-body h2 { font-size: 18px; margin: 32px 0 12px; }
              .md-body h3 { font-size: 15px; margin: 24px 0 10px; }
              .md-body h4 { font-size: 13px; margin: 20px 0 8px; }
              .md-body p { margin: 0 0 14px; color: ${t.muted}; font-size: 13px; line-height: 1.7; }
              .md-body strong { color: ${t.text}; font-weight: 600; }
              .md-body em { color: ${t.dim}; }
              .md-body pre {
                background: ${t.bg}; border: 1px solid ${t.border}; border-radius: 6px;
                padding: 14px 16px; overflow-x: auto; margin: 0 0 16px;
              }
              .md-body pre code {
                font-family: ${t.mono}; font-size: 11px; color: ${t.muted};
                white-space: pre; background: transparent; padding: 0;
              }
              .md-body :not(pre) > code {
                font-family: ${t.mono}; font-size: 11px; background: ${t.border}80;
                color: ${t.accent}; padding: 2px 5px; border-radius: 3px;
              }
              .md-body hr { border: none; border-top: 1px solid ${t.border}; margin: 24px 0; }
              .md-body a { color: ${t.accent}; text-decoration: none; }
              .md-body table {
                width: 100%; border-collapse: collapse; font-size: 12px;
                display: block; overflow-x: auto; margin: 0 0 16px;
              }
              .md-body tr { border-bottom: 1px solid ${t.border}; }
              .md-body th, .md-body td { padding: 8px 12px; text-align: left; }
              .md-body th { color: ${t.text}; font-weight: 600; background: ${t.surface}; }
              .md-body td { color: ${t.muted}; font-weight: 400; }
              .md-body blockquote {
                border-left: 3px solid ${t.accent}60; margin: 0 0 16px;
                padding: 8px 16px; color: ${t.dim}; font-style: italic;
              }
              .md-body blockquote p { margin: 0; }
              .md-body ul, .md-body ol {
                margin: 0 0 16px; padding-left: 22px; color: ${t.muted};
                font-size: 13px; line-height: 1.8;
              }
              .md-body li { margin-bottom: 4px; }
              .md-body input[type="checkbox"] { margin-right: 6px; accent-color: ${t.accent}; }
            `}</style>
            <div className="md-body" dangerouslySetInnerHTML={{ __html: renderMarkdown(markdown) }} />
            <p
              style={{
                marginTop: 40, fontSize: 11, color: t.dim, fontFamily: t.mono,
                borderTop: `1px solid ${t.border}`, paddingTop: 16,
              }}
            >
              {doc.source.type === "github"
                ? `Source: github.com/${doc.source.repo} · cached 5 min`
                : `Source: ${doc.path}`}
            </p>
          </>
        ) : (
          <div style={{ padding: 32, background: `${t.err}10`, border: `1px solid ${t.err}30`, borderRadius: 8 }}>
            <p style={{ margin: 0, color: t.err, fontSize: 14 }}>Could not load document</p>
            <p style={{ margin: "8px 0 0", color: t.muted, fontSize: 12 }}>
              {doc.source.type === "github"
                ? `Failed to fetch from github.com/${doc.source.repo} — check GITHUB_TOKEN has not expired.`
                : `Local file not found: ${doc.path}`}
            </p>
          </div>
        )}
      </main>
    </div>
  );
}

export function generateStaticParams() {
  return getDocsRegistry().map((d) => ({ id: d.id }));
}
