"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { matchesQuery } from "@/lib/docs-filter";

export type BrowserDoc = {
  id: string;
  title: string;
  section: string;
  docType?: string;
  tags: string[];
  path: string;
  remote?: string;
  generated?: boolean;
  updated?: string | null;
  badge?: { label: string; tone: "ok" | "warn" | "muted" | "accent" } | null;
};

export type BrowserGroup = { section: string; label: string; blurb: string; docs: BrowserDoc[] };

const TONE: Record<string, string> = {
  ok: "var(--tm-accent)",
  warn: "var(--tm-warn)",
  accent: "var(--tm-accent)",
  muted: "var(--tm-muted)",
};

export default function DocsBrowser({ groups }: { groups: BrowserGroup[] }) {
  const [q, setQ] = useState("");

  const filtered = useMemo(() => {
    if (!q.trim()) return groups;
    return groups
      .map((g) => ({ ...g, docs: g.docs.filter((d) => matchesQuery(d, q)) }))
      .filter((g) => g.docs.length > 0);
  }, [q, groups]);

  const total = groups.reduce((n, g) => n + g.docs.length, 0);
  const shown = filtered.reduce((n, g) => n + g.docs.length, 0);

  return (
    <div style={{ padding: "14px 18px", fontFamily: "var(--font-jetbrains-mono), monospace" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap" }}>
        <span style={{ color: "var(--tm-muted)", fontSize: 11.5 }}>
          <span style={{ color: "var(--tm-accent)" }}>$</span> find docs/ -name &apos;*.md&apos;
        </span>
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="search title, id, path, tag…"
          aria-label="Search documents"
          style={{
            flex: "1 1 260px",
            minWidth: 200,
            background: "var(--tm-bg)",
            border: "1px solid var(--tm-line)",
            borderRadius: 5,
            color: "var(--tm-ink)",
            padding: "6px 10px",
            fontSize: 11.5,
            fontFamily: "inherit",
            outline: "none",
          }}
        />
        <span style={{ color: "var(--tm-muted)", fontSize: 11 }}>
          {q ? `${shown}/${total}` : `${total} docs`}
        </span>
      </div>

      {filtered.length === 0 && (
        <div style={{ color: "var(--tm-muted)", fontSize: 12, padding: "20px 0" }}>
          No documents match <span style={{ color: "var(--tm-ink)" }}>{q}</span>.
        </div>
      )}

      {filtered.map((g) => (
        <div key={g.section} style={{ marginBottom: 22 }}>
          <div style={{ marginBottom: 7 }}>
            <div style={{ color: "var(--tm-ink)", fontSize: 12.5, fontWeight: 600 }}>
              # {g.label} <span style={{ color: "var(--tm-muted)", fontWeight: 400 }}>· {g.docs.length}</span>
            </div>
            <div style={{ color: "var(--tm-muted)", fontSize: 11, marginTop: 2 }}>{g.blurb}</div>
          </div>

          <div style={{ background: "var(--tm-panel)", border: "1px solid var(--tm-line)", borderRadius: 6 }}>
            {g.docs.map((d, i) => (
              <Link key={d.id} href={`/admin/docs/${d.id}`} style={{ textDecoration: "none", display: "block" }}>
                <div
                  title={`${d.title}\n${d.path}${d.tags.length ? `\ntags: ${d.tags.join(", ")}` : ""}`}
                  style={{
                    padding: "7px 14px",
                    borderBottom: i === g.docs.length - 1 ? "none" : "1px solid var(--tm-line)",
                    fontSize: 11.5,
                    display: "flex",
                    alignItems: "center",
                    gap: 10,
                  }}
                >
                  <span
                    style={{
                      flex: 1,
                      color: "var(--tm-accent)",
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                    }}
                  >
                    → {d.title}
                  </span>

                  {d.generated && (
                    <span style={{ color: "var(--tm-muted)", fontSize: 10 }} title="Regenerated by npm run docs:refresh">
                      generated
                    </span>
                  )}

                  <span style={{ width: 96, color: "var(--tm-muted)", fontSize: 10.5, flexShrink: 0 }}>
                    {d.docType ?? ""}
                  </span>

                  <span
                    style={{
                      width: 78,
                      flexShrink: 0,
                      fontSize: 10.5,
                      color: d.badge ? TONE[d.badge.tone] : "transparent",
                    }}
                  >
                    {d.badge?.label ?? ""}
                  </span>

                  <span style={{ width: 82, color: "var(--tm-muted)", fontSize: 10.5, flexShrink: 0 }}>
                    {d.updated ?? "—"}
                  </span>

                  <span
                    style={{ width: 58, fontSize: 10, flexShrink: 0, color: d.remote ? "var(--tm-accent)" : "var(--tm-muted)" }}
                    title={d.remote ? `Fetched from github.com/${d.remote}` : "Local file in this repo"}
                  >
                    {d.remote ? "github" : "local"}
                  </span>
                </div>
              </Link>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
